<?php

include_once('simple_config.features.inc');

/**
 * Implementation of hook_menu().
 */
function simple_config_menu() {
  $items = array();
  $items['home'] = array(
    'page callback' => 'simple_front_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Front page callback.
 */
function simple_front_page() {
  $context = context_load('front_page');
  context_set('context', 'front_page', $context);
  return '';
}
